# Numpy - Numerical Pyhon

### 1. ndarray(Numpy Dimensional Array)

In [2]:
# de facto standard
import numpy as np

In [ ]:
# flatten - 1차원으로 변환

In [3]:
a = np.arange(6) # a = np.array(range(6))
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
b = np.arange(16).reshape(-1, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
# 5, 6, 9, 10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [8]:
# 세번째 열까지는 X, 마지막 열은 Y
X, Y = b[:, :-1], b[:, -1]
X.shape, Y.shape

((4, 3), (4,))

In [9]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arrange(0, 1.1, 0.1)

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
# ones, zeros, empty