In [1]:
import numpy as np

In [4]:
# 1번
np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [6]:
# 2번 보기
m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
# 2-1번
m[1, 2]

7

In [9]:
# 2-2번
m[-1, -1]

14

In [10]:
# 2-3번
m[1, 1:3]

array([6, 7])

In [12]:
# 2-4번
m[1:3, 2]

array([ 7, 12])

In [15]:
# 2-5번
m[0:2, 3:5]

array([[3, 4],
       [8, 9]])

In [17]:
# 3-1번
m[np.logical_and(m % 3 == 0, m >0)]

array([ 3,  6,  9, 12])

In [18]:
# 3-2번
m[m % 4 == 1]

array([ 1,  5,  9, 13])

In [19]:
# 3-3번
m[np.logical_and(m % 3 == 0, m % 4 ==1 )]

array([9])

In [20]:
# 4번
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])