In [2]:
import numpy as np

In [4]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(ar)

numpy.ndarray

In [6]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [11]:
2 * a + b

array([12, 24, 36])

In [12]:
a == 2

array([False,  True, False])

In [13]:
b > 10

array([False,  True,  True])

In [14]:
( a == 2 ) & (b > 10)

array([False,  True, False])

In [15]:
c = np.array([[0, 1, 2], [3, 4, 5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
# 행의 개수
len(c)

2

In [17]:
# 열의 개수
len(c[0])

3

In [21]:
s = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
s

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [22]:
d = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]])


In [23]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [28]:
# a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [29]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [30]:
a = np.array([0, 1, 2, 3, 4])

In [31]:
a[2]

2

In [32]:
a[-1]

4

In [33]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
a[0, 0]

0

In [35]:
a[0, 1]

1

In [36]:
a[-1, -1]

5

In [37]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
a[0, :] # 첫번째 행 전체

array([0, 1, 2, 3])

In [41]:
a[:, 1] # 두번째 열 전체

array([1, 5])

In [42]:
a[1, 1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [44]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [46]:
m = np.array([[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9],
[10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
m[1, 2]

7

In [49]:
m[-1, -1]

14

In [50]:
m[1, 1:3]

array([6, 7])

In [51]:
m[1:3, 2]

array([ 7, 12])

In [52]:
m[0:2, 3:5]

array([[3, 4],
       [8, 9]])

In [53]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [54]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [55]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [56]:
a[ a % 2 == 0]

array([0, 2, 4, 6, 8])

In [57]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [58]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [59]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [62]:
a[[2, 0, 1], : ]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [64]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [70]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [71]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [76]:
x[x % 4 == 1] and x[x % 3 == 0] # 안되는 방법
x[x % 4 ==1 and x % 3 == 0] # 안되는 방법

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [80]:
x[np.logical_and(x % 4 == 1, x % 3 == 0)]

array([9])

In [81]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [82]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [83]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [84]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [85]:
x[0] + x[1]

3.0

In [86]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [87]:
x[0] + x[1]

'12'

In [90]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

<ipython-input-90-6ab12ec6e7a4>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
<ipython-input-90-6ab12ec6e7a4>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [91]:
np.log(0)

<ipython-input-91-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [92]:
np.exp(-np.inf)

0.0

In [93]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [95]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [96]:
c = np.zeros((5, 2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [97]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [98]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'abcde'
d

array(['abc', 'abcd', 'abcd', '', ''], dtype='<U4')

In [99]:
e = np.ones((2, 3, 4), dtype = 'i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [100]:
#b = np.zeros((2, 3))
f = np.ones_like(b, dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [101]:
g = np.empty((4,3))
g

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313],
       [2.54639495e-313, 2.97079411e-313, 3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313]])

In [110]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [113]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [114]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [115]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [117]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [121]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [124]:

a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [123]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [131]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [126]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [133]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [134]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [135]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [136]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [137]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [138]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [139]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [140]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [142]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [143]:
c.shape

(2, 3, 4)

In [147]:
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [145]:
c.shape

(3, 2, 4)

In [148]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [149]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [152]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [151]:
np.tile(a, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [163]:
a = np.zeros([3,3])
b = np.ones([3,2])
c = np.arange(10, 151, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [164]:
d = c.reshape(3, 5)
d

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [166]:
ab = np.hstack([a, b])
ab

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [168]:
abd = np.vstack(([ab, d]))
abd

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [169]:
np.tile(abd, (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

# 2차원 그리드 포인트 생성

In [175]:
x = np.arange(3)
x

array([0, 1, 2])

In [176]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [177]:
X, Y = np.meshgrid(x,y)
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [178]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [179]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]